/*Registe table
   Displays the the database table

*/
package com.gmail.yamkela22y;

import static com.gmail.yamkela22y.DataAccess.getConnection;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author YAMKELA MACWILI
 */
public class DataTable extends javax.swing.JFrame {

//    static final String DATABASE_URL = "jdbc:mysql://localhost/isipho_db";
//    static final String USER = "root";
//    static final String PASS = "yamkela22y!";
    /**
     * Creates new form DataTable
     */
    ImageIcon icon = null;
    public DataTable() throws ClassNotFoundException {
        super("Register");
        icon = new ImageIcon("C:\\Users\\YAMKELA MACWILI\\Documents\\NetBeansProjects\\Gift\\src\\com\\gmail\\yamkela22y\\isiphoLogo.jpg");
        setIconImage(icon.getImage());
        initComponents();
        jScrollPane1.setBackground(new Color(123,50,250)); // backgroung color
        tableLoad();
        setBounds(100, 100, 500, 350);//set position of the frame
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);
    }

     public final void tableLoad() throws ClassNotFoundException{
         
        PreparedStatement pstmt;
        Connection conn;
        
        try {
            String SQL = "SELECT * FROM isipho_db.isipho2";
            conn = getConnection();
            pstmt = conn.prepareStatement(SQL);   
            ResultSet rs = pstmt.executeQuery(); //use exectuteQuery for
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }    
        
        catch (SQLException e) {
            
           JOptionPane.showMessageDialog(null, e);
        } 
     }
             
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 40, 450, 220));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Print Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gmail/yamkela22y/isiphoLogo.PNG"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(51, 0, 51))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MessageFormat header = new MessageFormat("Register");
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");
        
        try{
            jTable1.print(JTable.PrintMode.NORMAL,header,footer );
        }
        catch(PrinterException e){
            JOptionPane.showMessageDialog(null,e);
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
