//Application
package com.gmail.yamkela22y;

import static com.gmail.yamkela22y.DataAccess.close;
import static com.gmail.yamkela22y.DataAccess.delete;
import static com.gmail.yamkela22y.DataAccess.getConnection;
import static com.gmail.yamkela22y.DataAccess.upDate;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author YAMKELA MACWILI
 */
public class IsiphoApplication extends javax.swing.JFrame {
    
    private Gift gift = null;
    ImageIcon icon = null;

    /**
     * Creates new form IsiphoApplication
     */
    public IsiphoApplication() {
        initComponents();
        //setting an icon
        icon = new ImageIcon("C:\\Users\\yamke\\OneDrive\\NetBeansProjects\\IsiphoRegistrationForm\\src\\com\\gmail\\yamkela22y\\isiphoLogo.jpg");
        setIconImage(icon.getImage());
       
        setVisible(true);                       //displays the frame
        setResizable(false);                    //fixed size
        txtfName.requestFocus();                //Puts the curse in the first line(name)
        //Loads the table next to the register (Register page)
        try {
            tableLoad();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IsiphoApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblVillage = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtfName = new javax.swing.JTextField();
        txtlName = new javax.swing.JTextField();
        txtvill = new javax.swing.JTextField();
        txtCellNo = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        pnlApplications = new javax.swing.JPanel();
        btnUniversity = new javax.swing.JButton();
        btnCollege = new javax.swing.JButton();
        btnBasary = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtEmailField = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegister = new javax.swing.JTable();
        lblSearchLabel = new javax.swing.JLabel();
        bnApsCal = new javax.swing.JButton();
        jLbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ISIPHO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setLocation(new java.awt.Point(400, 100));
        setLocationByPlatform(true);
        setName("mianFrame"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirstName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(204, 0, 0));
        lblFirstName.setText("Full Name");
        getContentPane().add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 29));

        lblLastName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(204, 0, 0));
        lblLastName.setText("Last Name");
        getContentPane().add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 29));

        lblVillage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblVillage.setForeground(new java.awt.Color(204, 0, 0));
        lblVillage.setText("Village/Town");
        getContentPane().add(lblVillage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 29));

        lblPhoneNumber.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(204, 0, 0));
        lblPhoneNumber.setText("Phone Number");
        getContentPane().add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 29));

        txtfName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 250, 29));

        txtlName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtlName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtlName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 250, 29));

        txtvill.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtvill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtvillKeyReleased(evt);
            }
        });
        getContentPane().add(txtvill, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 250, 29));

        txtCellNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(txtCellNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 250, 29));

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 90, 30));

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 90, 30));

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 90, 30));

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 90, 30));

        pnlApplications.setBackground(new java.awt.Color(153, 153, 255));
        pnlApplications.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Applications", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N
        pnlApplications.setForeground(new java.awt.Color(0, 0, 153));
        pnlApplications.setFocusTraversalPolicyProvider(true);
        pnlApplications.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUniversity.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnUniversity.setText("University");
        btnUniversity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUniversityActionPerformed(evt);
            }
        });
        pnlApplications.add(btnUniversity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        btnCollege.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCollege.setText("College");
        btnCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollegeActionPerformed(evt);
            }
        });
        pnlApplications.add(btnCollege, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 90, 30));

        btnBasary.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnBasary.setText("Basary");
        btnBasary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasaryActionPerformed(evt);
            }
        });
        pnlApplications.add(btnBasary, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 90, 30));

        getContentPane().add(pnlApplications, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 310, 70));

        btnView.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnView.setText("View Register");
        btnView.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 160, 30));

        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 80, 30));

        btnLogOut.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 80, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 30));

        txtEmailField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(txtEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 250, 30));

        txtSearch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 190, 30));

        jLabel1.setBackground(new java.awt.Color(18, 30, 49));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Cell No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblRegister.setBackground(new java.awt.Color(204, 204, 204));
        tblRegister.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tblRegister.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegisterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegister);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 330, 260));

        lblSearchLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        getContentPane().add(lblSearchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 260, 60));

        bnApsCal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bnApsCal.setBorder(new javax.swing.border.MatteBorder(null));
        bnApsCal.setLabel("Calculate APS");
        bnApsCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnApsCalActionPerformed(evt);
            }
        });
        getContentPane().add(bnApsCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 110, 30));

        jLbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gmail/yamkela22y/isiphoLogo.PNG"))); // NOI18N
        getContentPane().add(jLbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUniversityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUniversityActionPerformed
        new Universities();
    }//GEN-LAST:event_btnUniversityActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        //displays a printable table
        try {
            new DataTable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IsiphoApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewActionPerformed

    //Clears the text fields
    private void clear() {
        txtfName.setText(null);
        txtlName.setText(null);
        txtvill.setText(null);
        txtCellNo.setText(null);
        txtEmailField.setText(null);
        txtSearch.setText(null);
        txtfName.requestFocus();            //Sets the curser
    }

    //Method that reads data from the database and load it to the table 
    public final void tableLoad() throws ClassNotFoundException {

        PreparedStatement pstmt;
        Connection conn;

        try {
            String SQL = "SELECT * FROM isipho_db.isipho2";
            conn = getConnection();
            pstmt = conn.prepareStatement(SQL);
            ResultSet rs = pstmt.executeQuery(); //use exectuteQuery for
            tblRegister.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollegeActionPerformed
        new Collegies();
    }//GEN-LAST:event_btnCollegeActionPerformed

    private void btnBasaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasaryActionPerformed
        new Bursaries();
    }//GEN-LAST:event_btnBasaryActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String fName = txtfName.getText();
        String lName = txtlName.getText();
        String vill = txtvill.getText();
        String cellNo = txtCellNo.getText();
        gift = new Gift(fName, lName, vill, cellNo);
        try {
            upDate(gift);
            tableLoad();    //Refresh the table
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int yesNo = JOptionPane.showConfirmDialog(this, "Do you want to delete ?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        if (yesNo == JOptionPane.YES_OPTION) {
            try {
                String fName = null;
                String lName = null;
                String vill = null;
                String cellNo = txtCellNo.getText();
                gift = new Gift(fName, lName, vill, cellNo);
                tableLoad();    //Refresh the table
                if (!"".equals(cellNo)) {
                    delete(gift);
                    clear();
                    tableLoad();    //Refresh the table
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter a number to delete a person");
                }
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        FeedBack feedBack = new FeedBack();
               
        String fName = txtfName.getText();
        feedBack.setApplicantName(fName);
        String lName = txtlName.getText();
        String vill = txtvill.getText();
        String cellNo = txtCellNo.getText();
       
        //Check if all the text fields are filled be adding to the database
        if (!"".equals(fName) || !"".equals(lName) || !"".equals(vill) || !"".equals(cellNo)) {
            try {
                gift = new Gift(fName, lName, vill, cellNo);
                DataAccess dataAccess = null;
                try {
                    dataAccess.add(gift);
                     tableLoad();    //Refresh the table
                } catch (SQLException | ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
                

                JOptionPane.showMessageDialog(null, fName + " " + lName + " Added Successfully", "Success", 1);

                
                feedBack.sendMail(txtEmailField.getText());
                clear();
                tableLoad();    //Refresh the table
            } //if there are some empty fields print error message 
            catch (Exception ex) {
                Logger.getLogger(IsiphoApplication.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        int yesNo = JOptionPane.showConfirmDialog(this, "Do you want to EXIT?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        if (yesNo == JOptionPane.YES_OPTION) {
            new LoginForm();
            dispose();
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int yesNo = JOptionPane.showConfirmDialog(this, "Do you want to EXIT?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        if (yesNo == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Good Bye!!!");
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtfNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfNameKeyReleased
        // Sets the text to uppercases
        int position = txtfName.getCaretPosition();
        txtfName.setText(txtfName.getText().toUpperCase());
        txtfName.setCaretPosition(position);
     
    }//GEN-LAST:event_txtfNameKeyReleased

    private void txtlNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlNameKeyReleased
        // Sets the text to uppercases
        int position = txtlName.getCaretPosition();
        txtlName.setText(txtlName.getText().toUpperCase());
        txtlName.setCaretPosition(position);
    }//GEN-LAST:event_txtlNameKeyReleased

    private void txtvillKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvillKeyReleased
        // Sets the text to uppercases
        int position = txtvill.getCaretPosition();
        txtvill.setText(txtvill.getText().toUpperCase());
        txtvill.setCaretPosition(position);
    }//GEN-LAST:event_txtvillKeyReleased

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        PreparedStatement pstmt;
        Connection conn;
        try {
            String SQL = "select Name, Surname, village, cellNo from isipho2 where cellNo = ?";
            conn = getConnection();
            pstmt = conn.prepareStatement(SQL);
            pstmt.setString(1, txtSearch.getText());

            ResultSet rs = pstmt.executeQuery(); //use executeUpdate delete, insert update create

            if (rs.next() == true) {
                String fName = rs.getString(1);
                String lName = rs.getString(2);
                String village = rs.getString(3);
                String cellNo = rs.getString(4);

                txtfName.setText(fName);
                txtlName.setText(lName);
                txtvill.setText(village);
                txtCellNo.setText(cellNo);
            }

            close(conn, pstmt, null);

        } catch (SQLException e) {
            try {
                throw e;
            } catch (SQLException ex) {
                Logger.getLogger(IsiphoApplication.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IsiphoApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void bnApsCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnApsCalActionPerformed
        new APSCalculator();
    }//GEN-LAST:event_bnApsCalActionPerformed
    //this event allows you to click on the table to Update/Delete
    private void tblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegisterMouseClicked
        DefaultTableModel recordTable = (DefaultTableModel)tblRegister.getModel();
        int selectedRow = tblRegister.getSelectedRow();
        
        txtfName.setText(recordTable.getValueAt(selectedRow,1).toString());
        txtlName.setText(recordTable.getValueAt(selectedRow,2).toString());
        txtvill.setText(recordTable.getValueAt(selectedRow,3).toString());
        txtCellNo.setText(recordTable.getValueAt(selectedRow,4).toString());
    }//GEN-LAST:event_tblRegisterMouseClicked

    /**
     * @param args the command line arguments
     * @throws java.lang.Exception
     */
    public static void main(String args[]) throws Exception {
        new LoginForm();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnApsCal;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBasary;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCollege;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnUniversity;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbl_background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSearchLabel;
    private javax.swing.JLabel lblVillage;
    private javax.swing.JPanel pnlApplications;
    private javax.swing.JTable tblRegister;
    private javax.swing.JTextField txtCellNo;
    public static javax.swing.JTextField txtEmailField;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtfName;
    private javax.swing.JTextField txtlName;
    private javax.swing.JTextField txtvill;
    // End of variables declaration//GEN-END:variables
}
