//Login form
package com.gmail.yamkela22y;

import static com.gmail.yamkela22y.DataAccess.close;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author YAMKELA MACWILI
 */
public class LoginForm extends javax.swing.JFrame {

    static final String DATABASE_URL = "jdbc:mysql://localhost/isipho_db";
    static final String USER = "root";
    static final String PASS = "yamkela22y!";
 /**
  * 
  * @return
  * @throws SQLException
  * @throws ClassNotFoundException 
  */
    public static Connection getConnection() throws SQLException, ClassNotFoundException {
        Connection conn;
        conn = DriverManager.getConnection(DATABASE_URL, USER, PASS);
        return conn;
    }
    ImageIcon icon = null;
    /**
     * Creates new form SignUp
     */
    public LoginForm() {
        this.setVisible(true);
        setResizable(false);
        icon = new ImageIcon("C:\\Users\\yamke\\OneDrive\\NetBeansProjects\\IsiphoRegistrationForm\\src\\com\\gmail\\yamkela22y\\isiphoLogo.jpg");
        setIconImage(icon.getImage());
        setDefaultCloseOperation(3); //JFrame.EXIT_ON_CLOSE
        setBounds(400, 200, 50, 50);//set position of the frame
        initComponents();
        jTextField1.requestFocus();
    }
    //Clear the text fields
    private void clear() {
        jTextField1.requestFocus();
        jTextField1.setText(null);
        JPswd.setText(null);
    }
    /**
     * 
     * @throws ClassNotFoundException
     * @throws SQLException 
     */
     public void singIn() throws ClassNotFoundException, SQLException{
        PreparedStatement pstmt;
        Connection conn;
        ResultSet rs = null;
        
        try {
            if (!"".equals(jTextField1.getText()) || !"".equals(JPswd.getText())) {
            
                String sql = "INSERT INTO isipho_db.admins(username, password) VALUES(?,?)";
                conn = DriverManager.getConnection(DATABASE_URL, USER, PASS);
             
                pstmt = conn.prepareStatement(sql);    
                pstmt.setString(1, jTextField1.getText());
                pstmt.setString(2, JPswd.getText());
                pstmt.executeUpdate(); //use exectuteQuery for select
                JOptionPane.showMessageDialog(null, "Account Created Successfully, now you can login");
            }
            else{
                JOptionPane.showMessageDialog(null, "please provide username and password");
            }
                //close(conn,pstmt,null);       
        } 
        catch(java.sql.SQLIntegrityConstraintViolationException duplic){
             JOptionPane.showMessageDialog(null, "User name or password is already taken");
         }
        catch (SQLException e) {
            try {
                throw e;
            } catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
     }
     /**
      * 
      * @throws SQLException
      * @throws ClassNotFoundException 
      */
     public void login() throws SQLException, ClassNotFoundException {

        PreparedStatement pstmt;
        Connection conn;
       
        String usname = jTextField1.getText();
        String upass = JPswd.getText();
        try {
            String SQL = "SELECT  username,password FROM isipho_db.admins";
            conn = getConnection();
            pstmt = conn.prepareStatement(SQL);
            ResultSet rs = pstmt.executeQuery(); //use exectuteQuery for select

            while (rs.next()) {

                rs.getString("username");
                rs.getString("password");
                if (usname.equals(rs.getString("username")) && upass.equals(rs.getString("password"))) {
                    clear();
                    new IsiphoApplication();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect user name or passwor!!");
                }
            }
            close(conn, pstmt, rs); //close all resources 
        } catch (SQLException e) {
            throw e;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox = new javax.swing.JCheckBox();
        JPswd = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Username");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Password");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 30));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setToolTipText("User name");
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setName(""); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 260, 30));
        jTextField1.getAccessibleContext().setAccessibleDescription("");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 220, 100, -1));

        jCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        jCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 20, 20));

        JPswd.setBackground(new java.awt.Color(204, 204, 204));
        JPswd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JPswd.setForeground(new java.awt.Color(0, 0, 0));
        JPswd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        JPswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JPswdKeyPressed(evt);
            }
        });
        getContentPane().add(JPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 30));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Exit");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 253, 100, 20));

        jLabel3.setBackground(new java.awt.Color(102, 102, 255));
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 410, 80));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("LOGIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 80, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gmail/yamkela22y/icons/user-login-icon.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 80, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gmail/yamkela22y/icons/user-login-icon.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, 60));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gmail/yamkela22y/isiphoLogo.PNG"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 590, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            login();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActionPerformed
        if(jCheckBox.isSelected()){
            JPswd.setEchoChar((char)0);
        }
        else{
            JPswd.setEchoChar('*');
        }
        
    }//GEN-LAST:event_jCheckBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // try {
            System.exit(0);
         //   singIn();
//        } catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton2ActionPerformed
    //Moves the pointer to the next field when Enter key is Pressed
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            JPswd.requestFocus();     
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void JPswdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPswdKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                login();
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_JPswdKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPswd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
